### ISSUE TITLE
[Feature Request] Edit exercises

### ISSUE THREAD

**Issue by comatan96** [astashov/liftosaur#101]
Features:
* Name Change - e.g: I wrote `Smith-Machein Squat` and need to edit to `Smith-Machine Squat`
* Link/Notes - e.g: Link/notes for exercise tips

**Comment by yashrastogi** [comment]
Instead of putting equipment type in the exercise name, liftosaur separates equipment type keeping exercise the same (refer the docs)
So instead of you creating a custom exercise called "Smith-Machine Squat", you should be using the existing Squat exercise as following "Squat, Smith Machine"
And also name change feature for custom exercises is already implemented its just kinda obscured, in the workout page when you substitute an exercise there is an option to edit created custom exercises

As for link/notes, per exercise is there but yes per week or per day could be considered

**Comment by astashov** [comment]
> Name Change - e.g: I wrote Smith-Machein Squat and need to edit to Smith-Machine Squat

You can do it from the exercise picker, there's a way to edit custom exercises.

> Link/Notes - e.g: Link/notes for exercise tips

You can add it to the description for the program exercises, e.g. in the program text you can do:

```
// Do it properly
Squat / 3x8
```
