### ISSUE TITLE
Alternative Login and/or Self-Host

### ISSUE THREAD

**Issue by krillin666** [astashov/liftosaur#26]
First, let me start by saying that such an amazingly designed FOSS app like this not getting the deserved attention is unreal.
Thank you for making this app, it looks so much promising really !

I would like to have an account so that I can use the app between devices and be sure that I do not lose my data. However, I do not use Google and as such would like to know if it is possible to add an alternative login option ?

Also, it would be really nice if in the future you added a Self Hosting option, this would attract a lot of the Self-hosting user base who is looking for fitness solutions.

Thank you for your time.

**Comment by astashov** [comment]
I never got an email about this issue, so weird. Sorry for late response!

> First, let me start by saying that such an amazingly designed FOSS app like this not getting the deserved attention is unreal. Thank you for making this app, it looks so much promising really!

Thanks! :)

> I would like to have an account so that I can use the app between devices and be sure that I do not lose my data. However, I do not use Google and as such would like to know if it is possible to add an alternative login option?

Adding Google was me being lazy and not wanting to store any logins/passwords and all those flows for creating a user, logging in, resetting the password, etc, etc. I guess I could add them, but it's currently pretty low in priority list, sorry... PRs are welcome though, you know :)

> Also, it would be really nice if in the future you added a Self Hosting option, this would attract a lot of the Self-hosting user base who is looking for fitness solutions.

Yeah, 2 things are currently blocking that:
* I deploy the frontend to Netlify. Probably would make sense to move it to AWS instead, so everything would be on AWS and configurable via CDK. For self-hosting, it'd be a prerequisite, because custom setup of Netlify sounds complicated.
* liftosaur.com domain is hardcoded in many places, would need to make it configurable somehow.

Eventually I'll be there, but the first part with removing Netlify could be tricky...

**Comment by krillin666** [comment]
With the last update, the ability of exports and imports lets one use Nextcloud or Syncing for example to sync between mobile and desktop without account.
Thank you so much for this amazing app, keep the wonderful work !

**Comment by astashov** [comment]
Well, true, though it'll be a bit manual. :)
Thanks!
