### ISSUE TITLE
New state variables only accepted in 'if' clause

### ISSUE THREAD

**Issue by tom-a-horrocks** [astashov/liftosaur#30]
Hi,

Love the idea behind this app, thanks for making it.

I think I've found a bug in the script parsing functionality: I get an error when creating a new state variable, unless I'm in the 'true' branch of an if statement. For example, the following two code snippets (placed in the Finish Day Script) both result in **Error: Unknown state variable 'someVar'**:

```js
state.someVar = r[1][4] > 10 ? 15 : 10;
```

```js
if (completedReps[1] > 10) {
  state.someVar = 15;
} else {
  state.someVar = 10;
}
```

However, the following is fine:

```js
if (completedReps[1] > 10) {
  state.someVar = 15;
}
```
Is there a new way to declare state variables that I've missed?

**Comment by astashov** [comment]
You have to declare the variable in the section above, "Variables", like this:

<img width="466" alt="image" src="https://user-images.githubusercontent.com/12795/169290216-60bcd660-5213-4b6f-8227-06e7164cb429.png">

The reason I'm not allowing to declare a state variable in a finish day script is that the variables could be used not only in "Finish Day Script", but also in "Reps" and "Weight" fields of exercises, and they have the state that is stored through workouts. And regular (not state) variables that would only exist in the scope of "Finish Day Script" are not available, unfortunately.

But, the actual bug here is that you can use state variable inside the if/else without declaring it in the "Variables" section! I'll look into that, thanks a lot for reporting! :)

Also, there're some docs about scripting: https://www.liftosaur.com/docs/docs.html#state-variables-and-finish-day-script

**Comment by astashov** [comment]
It's not JS though, it's Liftoscript!
A super-duper simple language made specifically for the app. https://www.liftosaur.com/docs/docs.html#language-reference
 Syntax is similar to JS though.

`completedReps >= reps` is essentially the same as comparing each element of `completedReps` and `reps`, i.e. `completedReps[0] >= reps[0] && completedReps[1] >= reps[1] && ...` etc. Just a little syntax sugar :)

So, if:
```
reps = [5, 5, 5]
completedReps = [6, 1, 1]
```
then `completedReps >= reps` would return `false`, because second and third sets didn't reach the required minimum threshold of 5 reps.

Another difference of Liftoscript from Javascript is that you can specify the weight units. I.e. something like:

```
state.weight = state.weight + 10lb
```

would increase the weight variable by 10lb or by ~5kg, depending on whether you use kg or lb units.

**Comment by tom-a-horrocks** [comment]
Oh that's excellent! I saw the weight information in the language reference, but I think content about the array comparison is missing. I'll have a shot at adding it in a PR :).
