### ISSUE TITLE
Can't finish workout after adding new excercise

### ISSUE THREAD

**Issue by columndeeply** [astashov/liftosaur#41]
Hi! I saw the new "Add exercise" button and was testing it during today's workout but when I added the OHP I couldn't save the workout. Clicking on the "Finish the workout" didn't do anything (it might have reset the rest timer, I'm pretty sure I was resting longer than 14s before taking the pic...)

It looks like it might be suck on editing mode? I can see the "+" button but no "Finish Editing" button like I would usually see when editing an existing exercise.

Here's a screenshot:
![Screenshot_20230507-155326_Liftosaur](https://user-images.githubusercontent.com/106948293/236682208-11c9fb3a-5155-4c70-ba65-4e26e6681c26.png)

**Comment by astashov** [comment]
Oh yikes! Thanks for trying out the feature! I added it in case you feel like doing some more exercises, in addition to what your program prescribes.

> It looks like it might be suck on editing mode? I can see the "+" button but no "Finish Editing" button like I would usually see when editing an existing exercise.

No, that's expected. Since this is a completely new non-program empty exercise, I made the "+" button always visible, so it'd be easier to add sets for it, without having to switch to the edit mode.

But I know why it breaks, I see the exception in Rollbar. Gonna fix it now.

Thanks for reporting!
