### ISSUE TITLE
Weight shown as '0' on Cable exercises

### ISSUE THREAD

**Issue by zainthedev** [astashov/liftosaur#44]
I've only tested it on GZCLP, but to replicate:

1. Start a workout
2. Add a new exercise, set equipment to Cable, weight to 10kg, save
3. Weight should show as "0" on workout

Same thing happens if you add the exercise to the program before starting the workout.

**Comment by astashov** [comment]
Oh that's because I forgot to add default plates for kg for cable!
I fixed the default ones, so it won't happen for new accounts. To fix it for you, please go to Settings -> Available Equipment -> Cable -> Add new plate weight, and add the plates for cable that you have available in your gym.

Thanks for reporting!

**Comment by zainthedev** [comment]
Thanks for the fast response. Awesome app btw. Wonder if we can do dark mode... 😉 I might look at the code and see how difficult it would be haha

**Comment by astashov** [comment]
Dark mode is probably going to be a massive project :)
