### ISSUE TITLE
Variables with the same name reset warmups on all exercises

### ISSUE THREAD

**Issue by columndeeply** [astashov/liftosaur#52]
Hi! If there's two exercises with the same variable in them, changing the value of that variable will reset the warmup sets of both exercises.

Here's an example:
https://github.com/astashov/liftosaur/assets/106948293/a4d7b02a-bc20-4462-885b-afd1e1fe4941

Changing the "rm" variable on the Bench Press resets the Squat's warmup sets. I haven't tried but I'm pretty sure it only works if the variable you're changing is set to the first working set (since that's the one that's used to calculate the warmup weights).

Here's the program I used on the video: https://www.liftosaur.com/p/e475c652

**Comment by astashov** [comment]
It's not really variables with the same name reset warmups. It's just when you update a program, or any exercise within a program, it tries to regenerate the progress, and that wipes out the warmups (and also may wipe out some other stuff).

In bae578d I added a bit smarter logic, so that if you only change state variables, it will only apply to that exercise, and not other exercises in the workout. So, it should help!

**Comment by columndeeply** [comment]
Nice! Thank you!
