### ISSUE TITLE
[Feature Request] Exercise defaults

### ISSUE THREAD

**Issue by ozanmakes** [astashov/liftosaur#68]
Right now depending on the program, creating new exercises take a few too many clicks. I would like to set some global or per program (whatever makes sense to implement) defaults where I can set defaults for "Enable RPE", "Enable Rep Ranges", "Log RPE", "Enable Exercise Rest Timer". Right now the defaults don't match what I want and having to select all these for every exercise is time consuming.

This was also not ideal going from Workout Planner to Liftosaur because I had to go through each exercise and set to set these values.

**Comment by astashov** [comment]
You can duplicate existing exercises in the Web Editor (or in the app), that'd work similarly as having a default, I suppose.

For the planner - that makes sense, I guess it'd make sense to have a that as a setting on the planner itself - maybe as another section on the exercise line. It will currently enable some of those extra features though if you specify a timer, or RPE, or a range, etc. 

E.g. if you do:

```
Squat / 3x8-10 @8 120s
```

It'll automatically enable Rep Ranges, RPE and the Exercise Rest Timer because you provide per-exercise values for those.
Similarly for the Log RPE, maybe there should be some special syntax. Maybe like AMRAP? `@8+` would enable RPE logging.

**Comment by astashov** [comment]
Not very relevant anymore with the new program syntax.
