### ISSUE TITLE
[Feature Request] Warmup presets

### ISSUE THREAD

**Issue by ozanmakes** [astashov/liftosaur#69]
The program I'm following has some pre-determined types of warmups for each exercise:
<img width="997" alt="image" src="https://github.com/astashov/liftosaur/assets/111265/1159825d-f884-4e95-bb95-6b29f437e590">

It would be great to define this logic in one place and select using a dropdown when adding exercises.

Liftin' app has something like this:
![IMG_8920ABE79005-1](https://github.com/astashov/liftosaur/assets/111265/e183a359-a589-4de4-a9ff-406f518c92fa)

![image](https://github.com/astashov/liftosaur/assets/111265/7be19980-220e-4288-9382-1bfaf84a8404)

**Comment by astashov** [comment]
I like that. It could be configurable in your Settings, I suppose, with some defaults. Kinda similar to equipment, where we have built-in types, but you can add yours.

It's a bit tricky technically to add it (because it'd need to be added to all program sharings, program link generation, etc), but I already do that for equipment and custom exercises, so it could behave similarly.

**Comment by astashov** [comment]
Not super relevant since you can reuse warmups now, and also it's easy enough to copy paste them in the program text
