### ISSUE TITLE
[Feature Request] Automatically Update Current 1RM When Logging AMRAP

### ISSUE THREAD

**Issue by youhavejameswoods** [astashov/liftosaur#78]
It would be great if current 1RM was updated automatically when logging a set notated as AMRAP.  

For example, the logic could work as follows: 

FOR the current reps notated with a "+" for the currently assigned weight
IF there is no existing 1RM (for the above conditions) or if the calculated 1RM is > the current 1RM (for the above conditions)
THEN update current 1RM 

IF weight decreases, decrease 1RM based on weight decrease 
^^This would only work if you're trying to continually progress / not for planned significant deloads 

Not fully fleshed, but the idea is to limit the amount of custom code required for logging 1RM and developing lifting programs

**Comment by astashov** [comment]
Unfortunately that wouldn't work for a lot of programs, especially multi-week ones where some weeks have AMRAPs, and some don't. E.g. GZCL: The Rippler has a bunch of AMRAPs throughout the 12-week program, but you really test 1RM at the very end of macrocycle, and only at that point it'd make sense to update 1RM. 

That's why I'm hesitant to apply any default progression logic to AMRAPs - it's not always we want to update 1RM on AMRAPs.

**Comment by youhavejameswoods** [comment]
Makes sense and you are a much better expert than myself on all of the conditions that you have to account for across programs.  

I mostly wanted to throw the idea out there in case you come across a simplified way to update 1RMs as you continue to enhance the app.
